### ISSUE TITLE
Don't error on atom lookup on custom classes

### ISSUE THREAD

**Issue by jsmestad** [bratsche/twix#4]
I have several classes that are custom like `form-input` along with vanilla tailwind classes. If these go through `tw/1` calls, an error is returned. Is it possible to have unknown values fall through?

**Comment by iwarshak** [comment]
I am running into the same error I believe. `String.to_existing_atom` fails for my classes. I do use a custom tailwind prefix, so my classes are `tw-text-red-500` for example. Hopefully Twix supports custom prefixes?

**Comment by bratsche** [comment]
For now can you try pulling from master in your mix.exs and see if it works for what you need?

**Comment by iwarshak** [comment]
@bratsche works for me. the `to_existing_atom`  bug is gone and classes with custom prefix works too!
