### ISSUE TITLE
Custom classes support

### ISSUE THREAD

**Issue by theycallmehero** [bratsche/twix#7]
It would nice, if DefaultConfig would support different config (extending or appending).

**Comment by noozo** [comment]
+1

I have n custom tailwind classes in our projects that make this lib unusable, unfortunately, due to `:erlang.binary_to_existing_atom` being called for every class.

Ex:

![image](https://user-images.githubusercontent.com/3353/211328366-5c81b5d7-15da-45ab-a5dd-9ddd7faf6bb1.png)

**Comment by achord** [comment]
> I have n custom tailwind classes in our projects that make this lib unusable, unfortunately, due to :erlang.binary_to_existing_atom being called for every class.

I also have this issue

**Comment by Saldonas** [comment]
Same error, though slightly different problem is using some of the special syntax. For instance, I got this error when trying to use `text-white/90` which is just an opacity filter call, not a custom class at all.

**Comment by bratsche** [comment]
I think this was fixed by https://github.com/bratsche/twix/pull/11
